name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
  - cron: "0 2 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest, nightly]
    
    runs-on: ubuntu-latest

    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec          
